<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
    <table>
        <tr>
            <th>name</th>
            <th>email</th>
            <th>role</th>
            <th>state</th>
        </tr>
        <tr>
            <td>${name}</td>
            <td>${email}</td>
            <td>${role}</td>
            <td>${state}</td>
        </tr>
    </table>
</div>
</body>
</html>